### ISSUE TITLE
making a dataset

### ISSUE THREAD

**Issue by cmacdonald** [jjfiv/fastrank#36]
John, I'm not clear on how to make a dataset. E.g. I have a dataframe with 3 columns: "qid", "features", "label" with types string, np.array and int, how do I make it into a dataset?

**Comment by jjfiv** [comment]
I know this question is ancient, but the best thing in-place so far is this ``CDataset.from_numpy``. This is definitely a point of improvement I'd like to make. 

Numpy's format for "string" vectors is quite strange and difficult to "casually" pass to C.

**Comment by cmacdonald** [comment]
Ok, I found from_numpy. I see it has docstrings which I can follow. Perhaps the README needs to link to a generated documentation? Or a very simple toy example notebook (imagine you have 2 queries, each with 2 docs, with 3 features, etc?

**Comment by cmacdonald** [comment]
John, how can I get predicted **scores** for each document in a CDataset? All I found was `evaluate()` and `predict_trecrun()`, neither of which are relevant.

**Comment by jjfiv** [comment]
I had been using the 'trecrun' path to get the scores out. Would you want a nested structure, e.g.,:

```python
qid = '321'
docid = 'web007'

scores: Dict[str, Dict[str, float]] = model.predict(dataset)

print(scores[qid][docid])
```

Or are you looking for more like, serving the model in production? For production, I was imagining serializing the model and executing it separately (whatever your production language is).

**Comment by cmacdonald** [comment]
An API somewhat like what you would propose would be appropriate.

I note however that your API looks more like `List[float] = dataset.predict(model)`

IIRC, your CDataset has qids as ints? https://github.com/jjfiv/fastrank/blob/master/fastrank/clib.py#L236
and docids arent passed into the dataset.

**Comment by jjfiv** [comment]
Ah, yeah, that's meant to be fixed eventually... numpy's 'string arrays' are so weird and custom that getting them across to another language is annoying. I want this to be usable for, e.g., TREC-CAR where the qids are not numeric.

I know ranksvm and ranklib had such APIs where you were meant to preserve the order of your dataset on either side, but that's always kind of struck my as really error-prone.

**Comment by jjfiv** [comment]
I also wanted to avoid the issue in RankLib where if your data was not sorted by query, it would interpret them as 'extra' queries.

**Comment by cmacdonald** [comment]
Order retention is a reasonable assumption for a numpy based API. All sklearn learners retain order.
You could have `List[List[float]]` if you want to retain query grouping.

**Comment by jjfiv** [comment]
It looks like we do have that information for the numpy round-trip path. My thinking on some of this is still in the 'people will use this as a CLI' even though the notebook part is obviously great.

I'll get out the dict-based API sometime today, and the flat list-based one will be a bit more work, since I'll need to review all the types of datasets (internally).

**Comment by cmacdonald** [comment]
thanks John.

**Comment by cmacdonald** [comment]
In general, I'm trying to move away from CLI APIs. 

I tried the current github. I'm using the numpy constructions of dataset. I can train a model, but, as you hinted, I cant get predictions as I the document names are not set. (I had to set  RUST_BACKTRACE=1 to get the backtrace). I cant see how to set document names in the CDataset API.

```
thread '<unnamed>' panicked at 'Name should be present!', src/json_api.rs:68:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1260:5
   3: fastrank::json_api::predict_scores
   4: fastrank::ffi::result_predict_scores
   5: _predict_scores
```

**Comment by jjfiv** [comment]
Thanks for trying it so quickly. To avoid a deeper refactor (and since you seem to be testing live) I just pushed a quick change that returns a single dictionary, where keys are indices and the values should be the predicted scores.

This avoids the 'missing names' issue.

**Comment by jjfiv** [comment]
It also should involve no client-side changes if I can pivot to returning a ``List[float]`` instead of a ``Dict[int, float]``.

**Comment by cmacdonald** [comment]
No ball.
```
  File "/site-packages/fastrank/clib.py", line 415, in predict_scores
    return model.predict_scores(self)
  File "/site-packages/fastrank/clib.py", line 154, in predict_scores
    json_str = _handle_rust_str(_handle_c_result(lib.predict_scores(self.pointer, dataset.pointer)))
  File "/site-packages/fastrank/clib.py", line 33, in _handle_c_result
    if c_result.error_message != ffi.NULL:
AttributeError: cdata 'void *' has no attribute 'error_message'
```

**Comment by jjfiv** [comment]
Pretty confident it works now. Sorry for the runaround!

**Comment by cmacdonald** [comment]
Ok, this works for me, great! I have an integration to make it easy to use in PyTerrier.
Would a release be possible this week?

If your __init__.py has a __version__ variable, you could change the API in the future, and I could adjust if needed.

**Comment by jjfiv** [comment]
Yep! I'll get a release out this afternoon or evening (EST). Would love to be included in PyTerrier 👍 

This the kind of thing you're looking for? (I don't use python frequently enough to know if ``__version__`` is typically a tuple or a string).

```python
VERSION_TUPLE = (0,7,0)
__version__ = '{}.{}.{}'.format(*VERSION_TUPLE)
```

I'm adding an accessor 'is_sampled' to the Dataset API that will be able to determine if the scores vector needs to be sparse (Dict) or can be dense (np.array). I'll probably add a separate ``decision_function`` that matches the sklearn intuition and always outputs an array, but has a keyword argument for dealing with missing values -- that way you won't have to switch on the ``__version__``.

**Comment by cmacdonald** [comment]
>This the kind of thing you're looking for? (I don't use python frequently enough to know if __version__ is typically a tuple or a string).

```
VERSION_TUPLE = (0,7,0)
__version__ = '{}.{}.{}'.format(*VERSION_TUPLE)
```
LGTM. Excellent

**Comment by jjfiv** [comment]
It lives: https://pypi.org/project/fastrank/0.7.0/#files

Colab updated (to make sure it still works on Google's wonky linux):
https://colab.research.google.com/drive/1IjF7yTin1XaNO_6mBNxAoQYTmF0nckk1#scrollTo=Okx9VaQBhf9I

A new colab with your original request (displaying the numpyisms) will be coming soon (#39).

Thanks for your help with these issues & use-cases.

**Comment by cmacdonald** [comment]
Fabulous. Here is the documentation of the integration:
https://pyterrier.readthedocs.io/en/latest/ltr.html#fastrank-coordinate-ascent

One final note is that a notebook wont pick up the stdout/stderr - I wonder if you can pick up Python's filehandle.

But great stuff!
